# Write a function so that the columns of the output matrix are powers of the input vector.

# The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

# HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [1]:
import numpy as np 
x=np.array([1,2,3,4,5]) 
N=5 
matrix = np.column_stack([x**(N-i-1) for i in range(N)])
print(matrix)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


# Problem Statement

# Write a function to find moving average in an array over a window:
#Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [28]:
import numpy as np

def moving_avg(a, n=3):
    asum = np.cumsum(a, dtype = float)
    asum[n:] = asum[n:] - asum[:-n]
    return asum[n-1:]/n

a = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
a1 = np.array(a)

np.array(moving_avg(a1, n=3)).round(2)


array([  5.  ,   4.67,   5.67,   6.67,   9.67,  28.67,  49.33,  72.67,
        84.  ,  93.33, 116.33])